import type { AstrologyCity } from "./astrology"

export const NEPAL_ASTROLOGY_CITIES: AstrologyCity[] = [
  {
    id: "np-bagmati-kathmandu",
    name: "Kathmandu",
    region: "Bagmati, Nepal",
    latitude: 27.7172,
    longitude: 85.324,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-gandaki-pokhara",
    name: "Pokhara",
    region: "Gandaki, Nepal",
    latitude: 28.2096,
    longitude: 83.9856,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-bagmati-lalitpur",
    name: "Lalitpur",
    region: "Bagmati, Nepal",
    latitude: 27.6588,
    longitude: 85.3247,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-bagmati-bhaktapur",
    name: "Bhaktapur",
    region: "Bagmati, Nepal",
    latitude: 27.671,
    longitude: 85.4298,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-bagmati-bharatpur",
    name: "Bharatpur",
    region: "Bagmati, Nepal",
    latitude: 27.6768,
    longitude: 84.4359,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-koshi-biratnagar",
    name: "Biratnagar",
    region: "Koshi, Nepal",
    latitude: 26.4525,
    longitude: 87.2718,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-madhesh-birgunj",
    name: "Birgunj",
    region: "Madhesh, Nepal",
    latitude: 27.0104,
    longitude: 84.8774,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-lumbini-butwal",
    name: "Butwal",
    region: "Lumbini, Nepal",
    latitude: 27.6866,
    longitude: 83.4323,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-koshi-dharan",
    name: "Dharan",
    region: "Koshi, Nepal",
    latitude: 26.8125,
    longitude: 87.2836,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-madhesh-janakpur",
    name: "Janakpur",
    region: "Madhesh, Nepal",
    latitude: 26.7288,
    longitude: 85.9263,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-bagmati-hetauda",
    name: "Hetauda",
    region: "Bagmati, Nepal",
    latitude: 27.4284,
    longitude: 85.0322,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-lumbini-nepalgunj",
    name: "Nepalgunj",
    region: "Lumbini, Nepal",
    latitude: 28.05,
    longitude: 81.6167,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-sudurpashchim-dhangadhi",
    name: "Dhangadhi",
    region: "Sudurpashchim, Nepal",
    latitude: 28.6833,
    longitude: 80.6,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-koshi-itahari",
    name: "Itahari",
    region: "Koshi, Nepal",
    latitude: 26.6667,
    longitude: 87.2833,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-lumbini-ghorahi",
    name: "Ghorahi",
    region: "Lumbini, Nepal",
    latitude: 28.0367,
    longitude: 82.4864,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-lumbini-siddharthanagar",
    name: "Siddharthanagar",
    region: "Lumbini, Nepal",
    latitude: 27.5,
    longitude: 83.45,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
  {
    id: "np-koshi-birtamod",
    name: "Birtamod",
    region: "Koshi, Nepal",
    latitude: 26.638,
    longitude: 87.989,
    timeZone: "Asia/Kathmandu",
    utcOffsetHours: 5.75,
  },
]

export const SRI_LANKA_ASTROLOGY_CITIES: AstrologyCity[] = [
  {
    id: "lk-western-colombo",
    name: "Colombo",
    region: "Western Province, Sri Lanka",
    latitude: 6.9271,
    longitude: 79.8612,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-central-kandy",
    name: "Kandy",
    region: "Central Province, Sri Lanka",
    latitude: 7.2906,
    longitude: 80.6337,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-southern-galle",
    name: "Galle",
    region: "Southern Province, Sri Lanka",
    latitude: 6.0535,
    longitude: 80.221,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-northern-jaffna",
    name: "Jaffna",
    region: "Northern Province, Sri Lanka",
    latitude: 9.6615,
    longitude: 80.0255,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-western-negombo",
    name: "Negombo",
    region: "Western Province, Sri Lanka",
    latitude: 7.2083,
    longitude: 79.8358,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-north-central-anuradhapura",
    name: "Anuradhapura",
    region: "North Central Province, Sri Lanka",
    latitude: 8.3114,
    longitude: 80.4037,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-eastern-trincomalee",
    name: "Trincomalee",
    region: "Eastern Province, Sri Lanka",
    latitude: 8.5874,
    longitude: 81.2152,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-eastern-batticaloa",
    name: "Batticaloa",
    region: "Eastern Province, Sri Lanka",
    latitude: 7.7102,
    longitude: 81.6924,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-southern-matara",
    name: "Matara",
    region: "Southern Province, Sri Lanka",
    latitude: 5.9549,
    longitude: 80.555,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-north-western-kurunegala",
    name: "Kurunegala",
    region: "North Western Province, Sri Lanka",
    latitude: 7.4863,
    longitude: 80.3647,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-sabaragamuwa-ratnapura",
    name: "Ratnapura",
    region: "Sabaragamuwa Province, Sri Lanka",
    latitude: 6.6828,
    longitude: 80.3992,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-uva-badulla",
    name: "Badulla",
    region: "Uva Province, Sri Lanka",
    latitude: 6.9934,
    longitude: 81.055,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-central-nuwara-eliya",
    name: "Nuwara Eliya",
    region: "Central Province, Sri Lanka",
    latitude: 6.9497,
    longitude: 80.7891,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-north-central-polonnaruwa",
    name: "Polonnaruwa",
    region: "North Central Province, Sri Lanka",
    latitude: 7.9403,
    longitude: 81.0188,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-northern-vavuniya",
    name: "Vavuniya",
    region: "Northern Province, Sri Lanka",
    latitude: 8.7542,
    longitude: 80.4982,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-southern-hambantota",
    name: "Hambantota",
    region: "Southern Province, Sri Lanka",
    latitude: 6.1241,
    longitude: 81.1185,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-western-gampaha",
    name: "Gampaha",
    region: "Western Province, Sri Lanka",
    latitude: 7.0917,
    longitude: 79.9942,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
  {
    id: "lk-western-sri-jayawardenepura-kotte",
    name: "Sri Jayawardenepura Kotte",
    region: "Western Province, Sri Lanka",
    latitude: 6.8941,
    longitude: 79.9025,
    timeZone: "Asia/Colombo",
    utcOffsetHours: 5.5,
  },
]
